/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'

import { useGLTF } from '@react-three/drei/core/useGLTF'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const [active, setActive] = useState(false)
  const [position, setPosition] = useState(false)

  useEffect(() => {
    document.body.style.cursor = active ? 'pointer' : 'auto'
  }, [active])

  const { nodes, materials } = useGLTF('/assets/compressed-building.glb')

  const group = useRef()

  useEffect(() => {
    if (group.current !== null) setPosition(group.current.position)
  }, [position])

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={group}
        castShadow
        receiveShadow
        geometry={nodes.StrijpS_Gebouw_02.geometry}
        material={materials.M_Building2}
        position={[144.373352, 0, -55.8524]}
        rotation={[Math.PI, -0.69813182, Math.PI]}
        userData={{ name: 'Parkeer garage', body: 'Over dit gebouw...' }}
        onClick={() =>
          props.playFocusAnimations(position.x, position.y, position.z)
        }
        onPointerOver={() => setActive(true)}
        onPointerOut={() => setActive(false)}
      />
    </group>
  )
}

useGLTF.preload('/assets/compressed-building.glb')
