/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'


export default function Model(props) {
  const group = useRef(null)
  const { nodes, materials } = useGLTF('/assets/Groundplane.glb') 
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials.M_GroundPlane}
        userData={{ name: 'Plane001' }}
      />
    </group>
  )
}

useGLTF.preload('/assets/Groundplane.glb')
