/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef(null)
  const { nodes, materials } = useGLTF('/assets/Marker.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Marker.geometry}
        position={[-100, 100, -100]}
        material={materials.M_Marker}
        rotation={[Math.PI / 2, 0, 0]}
        userData={{ name: 'Marker' }}
      />
    </group>
  )
}

useGLTF.preload('/assets/Marker.glb')
